import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const path = usePathname();

  return (
    <html lang="en">
      <body className="antialiased bg-white min-h-screen">

        {children}
      </body>
    </html>
  );
}
